apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 3
  template:
   metadata:
    labels:
     app: hello
   spec:
     containers:
     - name: hello
       image: alycert/hello
       imagePullPolicy: "Always"
       ports:
       - name: hello
         containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-ui
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
   app: hello
  type: LoadBalancer                      
