version: 2
jobs:
    build:
       docker:
       - image: circleci/golang:1.11
       working_directory: /go/Golang-Hello-World
       steps:
       - checkout
       - setup_remote_docker
       - add_ssh_keys:
            fingerprints: 
            - "8b:85:71:bb:ce:0b:16:d6:dc:9b:ec:aa:b5:43:6c:b5"
       
       - run:
           name: Build Image
           command: docker build -t hello .
    
       - run:
            name: Push Image
            command: |
               docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD
               docker tag hello alycert/hello:${CIRCLE_SHA1:0:10}
               docker push alycert/hello:${CIRCLE_SHA1:0:10}
       - run:
           command: |
               ssh -oStrictHostKeyChecking=no ${USER}@${HOST} "bash -s" < /go/Golang-Hello-World/deploy.sh
               
